### PR TITLE
WiP - GoCSI

### PR DESCRIPTION
**Pull request by akutz**
This patch introduces the Go CSI library "gocsi", a Go-based framework that enables developers to build stand-alone CSI endpoints and reuse the same code to create Go shared objects (plug-ins). The "gocsi" framework can load the Go plug-ins and communicate with them using gRPC via in-memory, piped-based network connections.

This framework can be used to provide centralized throttling, authentication, logging, etc. -- all the while still encouraging CSI endpoints to be built as stand-along programs.

The "gocsi" library looks at the environment variable `CSI_PLUGINS` for a CSV list of shared object file paths. These files are expected to be Go shared object files and will be loaded as plug-ins. A "gocsi" plug-in should export the following symbol:

```go
Endpoints map[string]func() interface{}
```

The `Endpoints` symbol is a map of endpoint providers to the functions used to construct them. The constructed object should adhere to the following interface:

```go
// Endpoint is a gRPC server that provides the CSI Controller,
// Identity, and Node services.
type Endpoint interface {
    Init(ctx context.Context) error
    Serve(ctx context.Context, li net.Listener) error
    Shutdown(ctx context.Context) error
}
```

A Go plug-in can provide multiple endpoint providers. The "gocsi" library will serve the Endpoints with a listener backed by fully-duplexed, in memory connection courtesy of `net.Pipe()`.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @jdef,

Please do not consider this for merge until I finish the README with some better documentation. Thanks.

**Comment by akutz** [comment]
Hi @jdef,

FYI, there's a reason I'm vendoring `proto` and `grpc`. It will become apparent when I write the README. Or we could select `glide` as an official dependency manager. Go's community is split on vendoring things. In part because they lack experience with real world issues IMO, but that's another matter altogether :)

**Comment by akutz** [comment]
Hi @jdef,

On Linux a `make test` will demonstrate the entire thing from scratch:

```bash
$ make test
ref=$(git ls-remote https://github.com/container-storage-interface/spec master | awk '{print $1}') && \
ref="${ref:-master}" && \
printf "// time: %s\n// spec: %s\nsyntax = \"proto3\";\npackage %s;\n" \
  "$(date)" \
  "container-storage-interface/spec:${ref}" \
  "csi" > csi/csi.proto && \
curl -sSL https://raw.githubusercontent.com/container-storage-interface/spec/master/spec.md | \
sed -n -e '/```protobuf$/,/```$/ p' | \
sed -e 's@^```.*$@////////@g' >> csi/csi.proto
protoc -I csi --go_out=plugins=grpc:csi csi/csi.proto
mkdir -p .build/pkg/linux_amd64
go install -pkgdir /home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/.build/pkg/linux_amd64
.build/pkg/linux_amd64/github.com/container-storage-interface/libraries/gocsi.a
make -C mock mock-csi-plugin.so
make[1]: Entering directory '/home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/mock'
ref=$(git ls-remote https://github.com/container-storage-interface/spec master | awk '{print $1}') && \
ref="${ref:-master}" && \
printf "// time: %s\n// spec: %s\nsyntax = \"proto3\";\npackage %s;\n" \
  "$(date)" \
  "container-storage-interface/spec:${ref}" \
  "csi" > csi/csi.proto && \
curl -sSL https://raw.githubusercontent.com/container-storage-interface/spec/master/spec.md | \
sed -n -e '/```protobuf$/,/```$/ p' | \
sed -e 's@^```.*$@////////@g' >> csi/csi.proto
protoc -I csi --go_out=plugins=grpc:csi csi/csi.proto
mkdir -p .build/pkg/linux_amd64
go install -buildmode plugin -pkgdir /home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/mock/.build/pkg/linux_amd64
cp -f .build/pkg/linux_amd64/github.com/container-storage-interface/libraries/gocsi/mock.a mock-csi-plugin.so
make[1]: Leaving directory '/home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/mock'
CSI_PLUGINS="/home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/mock/mock-csi-plugin.so" \
go test -v -pkgdir /home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/.build/pkg/linux_amd64
=== RUN   TestGoCSI
Running Suite: CSI
==================
Random Seed: 1497911307
Will run 1 of 1 specs

2017/06/19 18:28:29 loaded plug-in: /home/akutz/go/src/github.com/container-storage-interface/libraries/gocsi/mock/mock-csi-plugin.so
2017/06/19 18:28:29 registered endpoint: mock
2017/06/19 18:28:29 mock.Serve
2017/06/19 18:28:29 mock.Accept
2017/06/19 18:28:29 mock.ListVolumes StartingToken=1
2017/06/19 18:28:29 mock.Shutdown
•
Ran 1 of 1 Specs in 1.199 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped --- PASS: TestGoCSI (1.20s)
PASS
ok  	github.com/container-storage-interface/libraries/gocsi	1.206s
```

**Comment by jdef** [comment]
why closed?

**Comment by akutz** [comment]
Hi @jdef,

See this [other](https://github.com/container-storage-interface/examples/pull/1#issuecomment-310211354) comment. tl;dr - I will be resubmitting.

**Pull request closed without merging**
